# Generated by Django 3.2 on 2022-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
